version: '3.7'

services:
  core:
    image: ${CORE_DOCKER_IMAGE:?err}
    restart: unless-stopped
    ports:
      - ${CORE_P2P_PORT:?err}:${CORE_P2P_PORT:?err} # P2P
      - 127.0.0.1:${CORE_RPC_PORT:?err}:${CORE_RPC_PORT:?err} #RPC
    volumes:
      - core_data:/hth
      - ${HTHMATE_HOME_DIR:?err}/${CONFIG_NAME:?err}/core/hth.conf:/hth/.hthcore/hth.conf
    command:
      - helpthehomelessd
      - -masternodeblsprivkey=${CORE_MASTERNODE_OPERATOR_PRIVATE_KEY}

volumes:
  core_data:
